name: router_module
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: 8.3.0
  flutter:
    sdk: flutter
  favorites_module:
    path: ../favorites_module
  get_it: ^8.0.3
  movies_module:
    path: ../movies_module
  shared_module:
    path: ../shared_module

dev_dependencies:
  auto_route_generator: 8.1.0
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
